[client]
toolbarMode = "viewer"
[server]
port = 8502

[theme]
primaryColor="#6eb52f"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"

#[theme]
#primaryColor="#d33682"
#backgroundColor="#002b36"
#secondaryBackgroundColor="#586e75"
#textColor="#fafafa"
#font="sans serif" # Accepted values (serif | sans serif | monospace)
