endpoint = "https://agent-runtime.generativeai.us-chicago-1.oci.oraclecloud.com" #replace if region other than chicago
agent_endpoint_id = "ocid1.genaiagentendpoint.oc1......" #replace with your OCID
